### ISSUE TITLE
TypeError: Cannot read property 'level' of undefined

### ISSUE THREAD

**Issue by at15** [at15/doc-viewer#23]
```
TypeError: Cannot read property 'level' of undefined
Please report this to https://github.com/chjj/marked.
 at Object.add (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/lib/util/toc.js:45:19)
    at TocRenderer.heading (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/lib/renderer/toc-renderer.js:17:9)
    at Parser.tok (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/node_modules/marked/lib/marked.js:973:28)
    at Parser.parse (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/node_modules/marked/lib/marked.js:924:17)
    at Function.Parser.parse (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/node_modules/marked/lib/marked.js:911:17)
    at marked (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/node_modules/marked/lib/marked.js:1207:19)
    at render (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/lib/render.js:28:12)
    at Object.withToc (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/lib/render.js:46:19)
    at /Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/lib/server.js:73:34
    at Layer.handle [as handle_request] (/Users/gpl/.nvm/versions/node/v0.12.7/lib/node_modules/doc-viewer/node_modules/express/lib/router/layer.js:95:5)
```

```
## title

content
```

**Comment by at15** [comment]
The markdown file did not have a h1, and h2 is the top most tag, the `toc` part can't handle markdown which does not use h123456 in right order.
